version: "3"

services:
  web:
    container_name: symfony-project
    image: project_web
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DOCKER_PHP_NGINX_IMAGE: ${DOCKER_PHP_NGINX_IMAGE:-webdevops/php-nginx:8.3}
    ports:
      - ${DOCKER_WEB_PORT:-80}:80
    volumes:
      - .:/app
    environment:
      - WEB_DOCUMENT_ROOT=/app/public

  database:
    container_name: project_mysql
    image: mysql:8.0.40
    environment:
      - MYSQL_ROOT_PASSWORD=${DOCKER_MYSQL_PASSWORD:-root}
      - MYSQL_DATABASE=${DOCKER_MYSQL_DATABASE:-symfony}
      - MYSQL_USER=${DOCKER_MYSQL_USER:-symfony}
      - MYSQL_PASSWORD=${DOCKER_MYSQL_PASSWORD:-ChangeMe}
    ports:
      - ${DOCKER_MYSQL_PORT:-3306}:3306